apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: DEPLOYMENTNAME
  labels:
    app: DEPLOYMENTNAME
  namespace: NAMESPACE
spec:
  template:
    metadata:
      labels:
        app: DEPLOYMENTNAME
    spec:
      containers:
      - name: DEPLOYMENTNAME
        image: IMAGENAME
        ports:
        - containerPort: 9091
          name: osmh-rep-cport
        resources:
          requests:
            memory: 1.5Gi
          limits:
            memory: 3Gi
      nodeSelector:
        cloud.google.com/gke-nodepool: himem-pool