apiVersion: v1
kind: Service
metadata:
  name: SERVICENAME
  namespace: NAMESPACE
  labels:
    app: SERVICENAME
spec:
  selector:
    app: SERVICENAME
  ports:
    - port: 9092
      protocol: TCP
      targetPort: osmh-ind-cport
