apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: DEPLOYMENTNAME
  labels:
    app: DEPLOYMENTNAME
  namespace: NAMESPACE
spec:
  template:
    metadata:
      labels:
        app: DEPLOYMENTNAME
    spec:
      containers:
      - name: DEPLOYMENTNAME
        image: IMAGENAME
        ports:
        - containerPort: 9092
          name: osmh-ind-cport
        resources:
          limits:
            memory: 4Gi
          requests:
            memory: 2Gi
      nodeSelector:
        cloud.google.com/gke-nodepool: himem-pool
