---
server:
  port: 9092
security:
  user:
    name: user
    password: pass
  basic.enabled: false            # Public API disable security on non-admin endpoints
management.security.enabled: true # Enable security on admin endpoints
endpoints.shutdown.enabled: true
spring:
  output:
    ansi:
      enabled: DETECT
  devtools:
    restart:
      enabled: false
  application:
    name: pasc-osmh-indexer
  jmx:
    default-domain: pasc-osmh-indexer
  boot:
    admin:
      url: http://localhost:8087
      username: user
      password: pass
      client.name: pasc-osmh-indexer
      turbine:
        clusters: default
        url: http://localhost:8989/turbine.stream
      routes:
        endpoints: env,metrics,log,trace,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump
      auto-deregistration: true
      auto-registration: true
logging:
  file: ${user.home}${file.separator}pasc-osmh-indexer${file.separator}pasc-osmh-indexer.log
  pattern:
    console: '%d{yyyy-dd-MM HH:mm:ss.SSS} %highlight(%-5level) %30.30((%M\)) %40.40((%file:%line\))
      - %message%n'
    file: '%d{yyyy-dd-MM HH:mm:ss.SSS}  %-5level  %30.30((%M\)) %40.40((%file:%line\))
      - %message%n'
  level:
    .: DEBUG
    org: ERROR
    net: WARN
    com: ERROR
    de: INFO
    eu.cessda.pasc: WARN
    eu.cessda.pasc.osmh.indexer: INFO
osmhIndexer:
  osmhHarvesterUrl: 'http://localhost:9091/v0/'
  incrementalPeriod: '0 0 */8 * * *'
  fullRun: ''
  repos:
  - url: 'https://oai.ukdataservice.ac.uk:8443/oai/provider'
    serviceProviderName: 'UKDS'
  - url: 'http://services.fsd.uta.fi/v0/oai'
    serviceProviderName: 'FSD'

---

spring:
  profiles: dev
  main:
        banner-mode: "off"
logging:
  pattern:
    console: '%message%n'
