---
# Copyright CESSDA ERIC 2017-2021
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %highlight(%-5level) %40.40((%file:%line\)) - %message%n'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS}  %-5level  %40.40((%file:%line\)) - %message%n'
  level:
    ROOT: WARN
    org.elasticsearch.client: ERROR
    eu.cessda.pasc.oci: INFO
elasticsearch:
  host: 127.0.0.1
  numberOfShards: 2
  numberOfReplicas: 0
restTemplateProps:
  connTimeout: 10000 # increased from 5 seconds to 10 seconds to deal with slower Nesstar repos
  connRequestTimeout: 5000 # 5 seconds
  readTimeout: 180000 # increased from 120 seconds to 180 seconds to deal with slower Nesstar repos
oaiPmh:
  metadataParsingDefaultLang:
    active: true
    lang: 'en'
  concatRepeatedElements: true
  concatSeparator: "<br>"
---
# For debugging
spring:
  config.activate.on-profile: local
  boot:
    admin:
      client:
        url: http://localhost:8087
        username: user
        password: password
logging:
  level:
    ROOT: INFO
    eu.cessda.pasc.oci: DEBUG
    eu.cessda.pasc.oci.repository: INFO
