---
server:
  port: 9902
#  context-path: '/osmh-repo'
security:
  user:
    name: user
    password: pass
  basic.enabled: false            # Public API disable security on non-admin endpoints
management.security.enabled: true # Enable security on admin endpoints
endpoints.shutdown.enabled: true
logging:
  file: ${user.home}${file.separator}pasc-oci${file.separator}pasc-oci.log
  pattern:
    console: '%d{yyyy-dd-MM HH:mm:ss.SSS} %highlight(%-5level) %30.30((%M\)) %40.40((%file:%line\))
      - %message%n'
    file: '%d{yyyy-dd-MM HH:mm:ss.SSS}  %-5level  %30.30((%M\)) %40.40((%file:%line\))
      - %message%n'
  level:
    .: WARN
    org: ERROR
    eu.cessda.pasc: DEBUG
    eu.cessda.pasc.oci.service: DEBUG
    eu.cessda.pasc.oci.repository: DEBUG
    eu.cessda.pasc.oci.helpers: DEBUG
    net: WARN
    com: ERROR
spring:
  mail:
    host: svboexc02.gesis.intra
  output:
    ansi:
      enabled: DETECT
  devtools:
    restart:
      enabled: false
  application:
    name: pasc-oci
  jmx:
    default-domain: pasc-oci
  boot:
    admin:
#     url: http://localhost:8087 For dev, stg & prod set this at the specific active profile. Run app with profile set
      username: user
      password: pass
      client.name: pasc-oci
      turbine:
        clusters: default
        url: http://localhost:8989/turbine.stream
      routes:
        endpoints: env,metrics,log,trace,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump
      auto-deregistration: true
      auto-registration: true
      period: 30000
elasticsearch:
  clustername: elasticsearch
  host: 127.0.0.1
  port: 9300

osmhConsumer:
  languages: ['en', 'fi', 'de']
  harvester:
    url: 'http://localhost:9091'
    version: 'v0'
  endpoints:
    supportedApiVersions:
      - v0
    supportedRecordTypes:
      - CMMStudy
    repos:
      - url: https://oai.ukdataservice.ac.uk:8443/oai/provider
        name: 'UK Data Service'
        handler: 'https://pasc-dev.cessda.eu/osmh-repo'
      - url: http://services.fsd.uta.fi/v0/oai
        name: 'Finish Data Services'
        handler: 'https://pasc-dev.cessda.eu/osmh-repo'
      - url: https://dbk.gesis.org/dbkoai
        name: 'GESIS'
        handler: 'https://pasc-dev.cessda.eu/osmh-repo'
      #** Note dirty extra "/" workaround for GESIS who separate records to different metadata prefix per language ***#
      - url: https://dbk.gesis.org/dbkoai/
        name: 'GESIS De'
        handler: 'https://pasc-dev.cessda.eu/osmh-repo'
  restTemplateProps:
    connTimeout: 5000
    connRequestTimeout: 5000
    readTimeout: 120000
    verifySSL: false

---
spring:
  profiles: dev
  main:
        banner-mode: "off"
  boot:
    admin:
      url: http://localhost:8087

---
spring:
  profiles: local
  main:
        banner-mode: "off"
  boot:
    admin:
      url: http://localhost:8087
osmhConsumer:
  languages: ['en', 'fi', 'de']
  endpoints:
    repos:
      - url: https://oai.ukdataservice.ac.uk:8443/oai/provider
        name: 'UK Data Service'
        handler: 'http://localhost:9091'
      - url: http://services.fsd.uta.fi/v0/oai
        name: 'Finish Data Services'
        handler: 'http://localhost:9091'
      - url: https://dbk.gesis.org/dbkoai
        name: 'GESIS'
        handler: 'http://localhost:9091'
      - url: https://dbk.gesis.org/dbkoai/
        name: 'GESIS De'
        handler: 'http://localhost:9091'

---
spring:
  profiles: test
  main:
        banner-mode: "off"
osmhConsumer:
  languages: ['en', 'fi', 'sv', 'de']
server:
  port: 9999
