---
server:
  port: 9091
security:
  user:
    name: user
    password: pass
  basic.enabled: false            # Public API disable security on non-admin endpoints
management.security.enabled: true # Enable security on admin endpoints
endpoints.shutdown.enabled: true
spring:
  output:
    ansi:
      enabled: DETECT
  devtools:
    restart:
      enabled: false
  application:
    name: pasc-osmh-handler.oai-pmh
  jmx:
    default-domain: pasc-osmh-handler.oai-pmh
  boot:
    admin:
#     url: http://localhost:8087 For dev, stg & prod set this at the specific active profile. Run app with profile set
      username: user
      password: pass
      client.name: pasc-osmh-handler.oai-pmh
      turbine:
        clusters: default
        url: http://localhost:8989/turbine.stream
      routes:
        endpoints: env,metrics,log,trace,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump
      auto-deregistration: true
      auto-registration: true
logging:
  file: ${user.home}${file.separator}pasc-osmh-handler${file.separator}pasc-osmh-handler.oai-pmh.log
  pattern:
    console: '%d{yyyy-dd-MM HH:mm:ss.SSS} %highlight(%-5level) %30.30((%M\)) %40.40((%file:%line\))
      - %message%n'
    file: '%d{yyyy-dd-MM HH:mm:ss.SSS}  %-5level  %30.30((%M\)) %40.40((%file:%line\))
      - %message%n'
  level:
    .: DEBUG
    org: ERROR
    net: WARN
    com: ERROR
    de: INFO
    eu.cessda.pasc.harvesting: WARN
    eu.cessda.pasc.harvesting.HarvesterReport: INFO
osmhhandler:
  oaiPmh:
    supportedApiVersions:
      - v0
    supportedRecordTypes:
      - CMMStudy
    repos:
      - url: https://oai.ukdataservice.ac.uk:8443/oai/provider
        preferredMetadataParam: ddi
      - url: www.test-repo2.com
        preferredMetadataParam: 3.2
    metadataParsingDefaultLang:
      active: true
      lang: 'en'
    concatenateRepeatedElements: true
    concatenateSeparator: "+<br>"
    publicationYearDefault: 1970
  restTemplateProps:
    connTimeout: 5000
    connRequestTimeout: 5000
    readTimeout: 5000
    verifySSL: false

---
spring:
  profiles: test
  main:
        banner-mode: "off"
osmhhandler:
  oaiPmh:
    supportedRecordTypes:
      - Study
      - StudyGroup
      - Variable
      - Question
      - CMM
    repos:
      - url: https://oai.ukdataservice.ac.uk:8443/oai/provider
        preferredMetadataParam: ddi
      - url: www.test-repo2.com
        preferredMetadataParam: 3.2
    metadataParsingDefaultLang:
      active: true
      lang: 'en'
    publicationYearDefault: 1970

---
spring:
  profiles: local
  boot:
    admin:
      url:
logging:
  pattern:
    console: '%message%n'

---
spring:
  profiles: dev
  main:
        banner-mode: "off"
  boot:
    admin:
      url: http://localhost:8087
logging:
  pattern:
    console: '%message%n'
