---
server:
  port: 9091
logging:
  file: ${user.home}${file.separator}pasc-osmh-handler${file.separator}pasc-osmh-handler.oai-pmh.log
  pattern:
    console: '%d{yyyy-dd-MM HH:mm:ss.SSS} %highlight(%-5level) %30.30((%M\)) %40.40((%file:%line\))
      - %message%n'
    file: '%d{yyyy-dd-MM HH:mm:ss.SSS}  %-5level  %30.30((%M\)) %40.40((%file:%line\))
      - %message%n'
  level:
    .: DEBUG
    org: ERROR
    net: WARN
    com: ERROR
    de: INFO
    eu.cessda.pasc.harvesting: WARN
    eu.cessda.pasc.harvesting.HarvesterReport: INFO
osmhhandler:
  oaiPmh:
    supportedApiVersions:
      - v0
    supportedRecordTypes:
      - Study
      - StudyGroup
      - Variable
      - Question
      - CMM
    repos:
      - url: www.test-repo.com
        preferredMetadataVersion: 2.5
      - url: www.test-repo2.com
        preferredMetadataVersion: 3.2
  restTemplateProps:
    connTimeout: 5000
    connRequestTimeout: 5000
    readTimeout: 5000

---

spring:
  profiles: dev
  main:
        banner-mode: "off"
logging:
  pattern:
    console: '%message%n'
