---
server:
  port: 9902
#  context-path: '/osmh-repo'
security:
  user:
    name: user
    password: pass
  basic.enabled: false            # Public API disable security on non-admin endpoints
management.security.enabled: true # Enable security on admin endpoints
endpoints.shutdown.enabled: true
logging:
  file: ${user.home}${file.separator}pasc-oci${file.separator}pasc-oci.log
  pattern:
    console: '%d{yyyy-dd-MM HH:mm:ss.SSS} %highlight(%-5level) %30.30((%M\)) %40.40((%file:%line\))
      - %message%n'
    file: '%d{yyyy-dd-MM HH:mm:ss.SSS}  %-5level  %30.30((%M\)) %40.40((%file:%line\))
      - %message%n'
  level:
    .: WARN
    org: ERROR
    eu.cessda.pasc: INFO
    eu.cessda.pasc.oci.service: DEBUG
    eu.cessda.pasc.oci.repository: DEBUG
    eu.cessda.pasc.oci.helpers: DEBUG
    net: WARN
    com: ERROR
spring:
  mail:
    host: svboexc02.gesis.intra
  output:
    ansi:
      enabled: DETECT
  devtools:
    restart:
      enabled: false
  application:
    name: pasc-oci
  jmx:
    default-domain: pasc-oci
  boot:
    admin:
#     url: http://localhost:8087 For dev, stg & prod set this at the specific active profile. Run app with profile set
      username: user
      password: pass
      client.name: pasc-oci
      turbine:
        clusters: default
        url: http://localhost:8989/turbine.stream
      routes:
        endpoints: env,metrics,log,trace,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump
      auto-deregistration: true
      auto-registration: true
      period: 30000
elasticsearch:
  clustername: elasticsearch
  host: 127.0.0.1
  port: 9300
  numberOfShards: 2
  numberOfReplicas: 0
osmhConsumer:
  languages: ['en', 'fi', 'de', 'nl', 'fr']
  harvester:
    url: 'http://localhost:9091'
    version: 'v0'
  endpoints:
    supportedApiVersions:
      - v0
    supportedRecordTypes:
      - CMMStudy
    repos:
      - url: https://oai.ukdataservice.ac.uk:8443/oai/provider
        name: 'UK Data Service'
        handler: 'https://pasc-dev.cessda.eu/osmh-repo'
      - url: https://dbk.gesis.org/dbkoai2/
        name: 'GESIS'
        handler: 'https://pasc-dev.cessda.eu/osmh-repo'
      - url: http://services.fsd.uta.fi/v0/oai
        name: 'Finish Data Services'
        handler: 'https://pasc-dev.cessda.eu/osmh-repo'
    connTimeout: 5000
    connRequestTimeout: 5000
    readTimeout: 120000 # 65secs (65_000ms) NOTE handler is less (60_000).
    verifySSL: false

---
spring:
  profiles: dev
  main:
        banner-mode: "off"
  boot:
    admin:
      client:
        prefer-ip: true
      url: http://localhost:8087
logging:
  level:
    eu.cessda.pasc.oci.service: INFO
    eu.cessda.pasc.oci.repository: INFO
    eu.cessda.pasc.oci.helpers: INFO
elasticsearch:
  host: cessda-pasc-es-dev-cluster
  numberOfShards: 2
  numberOfReplicas: 2
---
spring:
  profiles: staging
  main:
        banner-mode: "off"
  boot:
    admin:
      client:
        prefer-ip: true
      url: http://localhost:8087
logging:
  level:
    eu.cessda.pasc.oci.service: INFO
    eu.cessda.pasc.oci.repository: INFO
    eu.cessda.pasc.oci.helpers: INFO
elasticsearch:
  host: cessda-pasc-es-staging-cluster
  numberOfShards: 2
  numberOfReplicas: 2
---
  spring:
    profiles: live
    main:
          banner-mode: "off"
    boot:
      admin:
        client:
          prefer-ip: true
        url: http://localhost:8087
  logging:
    level:
      eu.cessda.pasc.oci.service: INFO
      eu.cessda.pasc.oci.repository: INFO
      eu.cessda.pasc.oci.helpers: INFO
  elasticsearch:
    host: cessda-pasc-es-live-cluster
    numberOfShards: 2
    numberOfReplicas: 2
---
spring:
  profiles: local
  main:
        banner-mode: "off"
  boot:
    admin:
      url: http://localhost:8087
logging:
  level:
    eu.cessda.pasc.oci.service: DEBUG
    eu.cessda.pasc.oci.repository: DEBUG
    eu.cessda.pasc.oci.helpers: DEBUG
osmhConsumer:
  languages: ['en', 'fi', 'de', 'fr']
  endpoints:
    repos:
      - url: https://oai.ukdataservice.ac.uk:8443/oai/provider
        name: 'UK Data Service'
        handler: 'http://localhost:9091'
      - url: http://services.fsd.uta.fi/v0/oai
        name: 'Finish Data Services'
        handler: 'http://localhost:9091'
      - url: http://fors-nesstar.unil.ch/oai-pmh
        name: 'FORS Data Service (Nesstar)'
        handler: 'http://localhost:9842'
      - url: http://nesstar.ukdataservice.ac.uk/oai-pmh
        name: 'UK Data Service (Nesstar)'
        handler: 'http://localhost:9842'
      - url: http://nesstar.ucd.ie/oai-pmh
        name: 'ISSDA (Nesstar)'
        handler: 'http://localhost:9842'
      - url:  http://nesstar.sciences-po.fr/oai-pmh
        name: 'Progedo (Nesstar)'
        handler: 'http://localhost:9842'
---
spring:
  profiles: test
  main:
        banner-mode: "off"
osmhConsumer:
  languages: ['en', 'fi', 'sv', 'de']
server:
  port: 9999
elasticsearch:
  numberOfShards: 1
  numberOfReplicas: 0
