---
# Copyright CESSDA ERIC 2017-2019
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
server:
  port: 9902
management:
  endpoints:
    health.show-details: true
    shutdown.enabled: true
    web:
      exposure.include: '*'
logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %highlight(%-5level) %40.40((%file:%line\)) - %message%n'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS}  %-5level  %40.40((%file:%line\)) - %message%n'
  level:
    ROOT: WARN
    eu.cessda.pasc: INFO
    eu.cessda.pasc.oci.service: INFO
    eu.cessda.pasc.oci.repository: INFO
    eu.cessda.pasc.oci.helpers: INFO
    eu.cessda.pasc.oci.configurations.PerfRequestSyncInterceptor: DEBUG
spring:
  mail:
    host: pasc-mailrelay
  output:
    ansi:
      enabled: DETECT
  devtools:
    restart:
      enabled: false
  application:
    name: pasc-oci
  jmx:
    default-domain: pasc-oci
  boot:
    admin:
      client:
        name: pasc-oci
        instance:
          metadata:
            user:
              # Send the username and password for authentication to Spring Boot Admin
              name: ${spring.security.user.name}
              password: ${spring.security.user.password}
      turbine:
        clusters: default
        url: http://localhost:8989/turbine.stream
      routes:
        endpoints: env,metrics,log,trace,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump
      auto-deregistration: true
      auto-registration: true
      period: 30000
  security:
    user:
      name: user
      password: password
      roles: ACTUATOR
elasticsearch:
  clustername: elasticsearch
  host: 127.0.0.1
  port: 9300
  numberOfShards: 2
  numberOfReplicas: 0
osmhConsumer:
  languages: ['cs', 'da', 'de', 'el', 'en', 'et', 'fi', 'fr', 'hu', 'it', 'nl', 'no', 'pt', 'sk', 'sl', 'sr', 'sv']
  delay:
    # Auto Starts after delay of 2 seconds at startup
    initial: '2000'
    fixed: '315360000000'
  daily:
    # Daily Harvest and Ingestion run at 00:01am.
    run: '0 01 00 * * *'
    # Then run every Sunday at 09:00
    sunday.run: '0 00 09 * * SUN'
  # The OAI-PMH handler is predefined, this is used for setting external handlers
  endpoints:
    harvesters:
      NESSTAR:
        url: 'http://localhost:9842'
        version: 'v0'
    supportedRecordTypes:
      - CMMStudy
    repos:
      - url: http://194.117.18.18:6003/v0/oai
        name: 'APIS'
        handler: 'OAI-PMH'
        preferredMetadataParam: oai_ddi25
      - url: https://data2.aussda.at/oai
        name: 'AUSSDA'
        handler: 'OAI-PMH'
        preferredMetadataParam: oai_ddi
      - url: https://easy.dans.knaw.nl/oai/
        name: 'DANS'
        handler: 'OAI-PMH'
        preferredMetadataParam: oai_ddi25_nl
      - url: https://kuha.sa.dk/v0/oai
        name: 'DNA'
        handler: 'OAI-PMH'
        preferredMetadataParam: oai_ddi25_en
        # Placeholder for FORS
        #     - url: ''
        #     name: 'FORS'
        #     handler: 'OAI-PMH'
      - url: http://services.fsd.uta.fi/v0/oai
        name: 'FSD'
        handler: 'OAI-PMH'
        preferredMetadataParam: oai_ddi25
      - url: https://dbkapps.gesis.org/dbkoai3
        name: 'GESIS'
        handler: 'OAI-PMH'
        preferredMetadataParam: oai_ddi25
      - url: https://data.sciencespo.fr/oai
        name: 'Progedo'
        handler: 'OAI-PMH'
        setSpec: CDSP
      - url: http://147.213.4.44:6003/v0/oai
        name: 'SASD'
        handler: 'OAI-PMH'
        preferredMetadataParam: oai_ddi25
      - url: https://snd.gu.se/en/oai-pmh
        name: 'SND'
        handler: 'OAI-PMH'
        setSpec: discipline:social-science
      - url: https://dataverse.arch.be/oai
        name: 'SODA'
        handler: 'OAI-PMH'
        preferredMetadataParam: oai_ddi
        defaultLanguage: fr
      - url: https://oai.ukdataservice.ac.uk:8443/oai/provider
        name: 'UKDS'
        handler: 'OAI-PMH'
        preferredMetadataParam: ddi
      - url: https://nesstar2.adp.fdv.uni-lj.si/oai-pmh
        name: 'ADP (Nesstar)'
        handler: 'NESSTAR'
      - url: http://nesstar.soc.cas.cz/oai-pmh
        name: 'CSDA (Nesstar)'
        handler: 'NESSTAR'
      - url: https://oai-pmh.nsd.no/oai-pmh
        name: 'NSD (Nesstar)'
        handler: 'NESSTAR'
      - url:  http://nesstar.sciences-po.fr/oai-pmh
        name: 'Progedo (Nesstar)'
        handler: 'NESSTAR'
        defaultLanguage: fr
      - url:  http://harvester.sodanet.gr:8080/oai/request
        name: 'SoDaNet (Nesstar)'
        handler: 'NESSTAR'
        defaultLanguage: el
      - url:  http://nesstar.unidata.unimib.it/oai-pmh
        name: 'Unidata (Nesstar)'
        handler: 'NESSTAR'
  restTemplateProps:
    connTimeout: 10000 # increased from 5 seconds to 10 seconds to deal with slower Nesstar repos
    connRequestTimeout: 5000 # 5 seconds
    readTimeout: 180000 # increased from 120 seconds to 180 seconds to deal with slower Nesstar repos
    verifySSL: true
osmhhandler:
  baseEndpoint: '/'
  oaiPmh:
    supportedApiVersions:
      - v0
    supportedRecordTypes:
      - CMMStudy
    metadataParsingDefaultLang:
      active: true
      lang: 'en'
    concatRepeatedElements: true
    concatSeparator: "+<br>"
    publicationYearDefault: 1970
  restTemplateProps:
    connTimeout: 10000 # increased from 5 seconds to 10 seconds to deal with slower Nesstar repos
    connRequestTimeout: 5000 # 5 seconds
    readTimeout: 180000 # increased from 120 seconds to 180 seconds to deal with slower Nesstar repos
    verifySSL: true
---
spring:
  profiles: gcp
  main:
    banner-mode: "off"
  boot:
    admin:
      client:
        instance:
          prefer-ip: true
        url: http://localhost:8087
  output.ansi.enabled: NEVER
logging:
  file: pasc-oci.log
  level:
    eu.cessda.pasc.oci.service: INFO
    eu.cessda.pasc.oci.repository: INFO
    eu.cessda.pasc.oci.helpers: INFO
    eu.cessda.pasc.oci.configurations.PerfRequestSyncInterceptor: INFO
elasticsearch:
  host: cdc-es  # must match profile name
  numberOfShards: 2
  numberOfReplicas: 2
osmhConsumer:
  daily:
    # The following variables are defined using cron notation
    run: ${OSMHCONSUMER_DAILY_RUN}
    sunday.run: ${OSMHCONSUMER_DAILY_SUNDAY_RUN}
  endpoints:
    harvesters:
      OAI-PMH:
        url: 'http://cdc-osmh-repo:9091'
        version: 'v0'
      NESSTAR:
        url: 'http://cdc-osmh-repo-nesstar:9842'
        version: 'v0'
osmhhandler:
  baseEndpoint: '/osmh-repo'
---
spring:
  profiles: local
  boot:
    admin:
      client:
        url: http://localhost:8087
        username: user
        password: password
logging:
  level:
    ROOT: INFO
    eu.cessda.pasc.oci: TRACE
---
spring:
  main:
    banner-mode: "off"
  profiles: test
logging:
  level:
    eu.cessda.pasc.oci.service.helpers.LanguageDocumentExtractor: DEBUG
    eu.cessda.pasc.oci.repository.DaoBase: DEBUG
osmhConsumer:
  endpoints:
    supportedRecordTypes:
      - Study
      - StudyGroup
      - Variable
      - Question
      - CMM
    harvesters:
      OAI-PMH:
        url: 'http://localhost:9091'
        version: 'v0'
    repos:
      - url: https://data2.aussda.at/oai/
        preferredMetadataParam: oai_ddi
        name: 'AUSSDA'
        handler: 'OAI-PMH'
      - url: http://services.fsd.uta.fi/v0/oai
        preferredMetadataParam: oai_ddi25
        setSpec: study_groups:energia
        name: 'FSD'
        handler: 'OAI-PMH'
      - url: https://oai.ukdataservice.ac.uk:8443/oai/provider
        preferredMetadataParam: ddi
        name: 'UKDS'
        handler: 'OAI-PMH'
      - url: http://services.fsd.uta.fi/v0/oai
        preferredMetadataParam: oai_ddi25
        name: 'UKDS-LANG-OVERRIDE'
        defaultLanguage: zz
        handler: 'OAI-PMH'
  delay:
    # For tests, the delay should be effectively disabled
    initial: '315360000000'
    fixed: '315360000000'
elasticsearch:
  clustername: test
osmhhandler:
  oaiPmh:
    metadataParsingDefaultLang:
      active: true
      lang: 'en'
    publicationYearDefault: 1970
